### ISSUE TITLE
Panic with empty file

### ISSUE THREAD

**Issue by cassiersg** [nrc/rustfmt#115]
When rustfmt is run with an empty file, it panics:
```
thread '<main>' panicked at 'position 0 does not resolve to a source location', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/codemap.rs:867
stack backtrace:
[...]
   5:     0x7ff667530109 - codemap::CodeMap::lookup_filemap_idx::h1bce8c06a778e65e9tz
   6:     0x7ff66752eb14 - codemap::CodeMap::lookup_char_pos::hcc754a5c462398d0Cfz
   7:     0x7ff668e60578 - visitor::FmtVisitor<'a>.visit..Visitor<'v>::visit_mod::h9604a78e71eb942fkSa
                        at /home/cassiersg/rustfmt/src/visitor.rs:247
   8:     0x7ff668ea750b - visit::walk_crate::h6150558082621252545
                        at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libsyntax/visit.rs:152
   9:     0x7ff668ea7269 - fmt_ast::h8b54e757388643aehXd
                        at /home/cassiersg/rustfmt/src/lib.rs:167
[...]
```
Should it be fixed here or is it an unsound behavior of `Codemap::lookup_char_pos` that should be fixed in rustc ?

**Comment by nrc** [comment]
It sounds like a bug in codemap, but perhaps we are violating its invariants by opening a zero length file? Worth investigating further.

**Comment by marcusklaas** [comment]
Has this been resolved?

**Comment by cassiersg** [comment]
I don't know if it's due to our changes or to upstream rustc changes, but it works now.
