### ISSUE TITLE
Panic on rust/src/libcore/fmt/mod.rs

### ISSUE THREAD

**Issue by mkpankov** [nrc/rustfmt#419]
```
mkpankov@mkpankov-ThinkPad-x240 ~/rust/src/libcore [master]
± % ➜  RUST_BACKTRACE=1 ~/rustfmt/target/debug/rustfmt --write-mode=diff fmt/mod.rs                                                                                                                          !2903
thread '<main>' panicked at 'Request to format inverted span: Loc { file: FileMap(fmt/mod.rs), line: 1417, col: CharPos(32) } to Loc { file: FileMap(fmt/mod.rs), line: 1415, col: CharPos(4) }', src/missed_spans.rs:54
stack backtrace:
   1:     0x7f17f8562940 - sys::backtrace::tracing::imp::write::he27ef2eb40e30753Plt
   2:     0x7f17f8569215 - panicking::log_panic::_<closure>::closure.39293
   3:     0x7f17f8568c61 - panicking::log_panic::h20a17353a34447751lx
   4:     0x7f17f852d783 - sys_common::unwind::begin_unwind_inner::hf876a8bedc1a7d89gds
   5:     0x7f17f852e0e8 - sys_common::unwind::begin_unwind_fmt::h69a2566a09092307mcs
   6:     0x5616b1a8955b - missed_spans::_<impl>::format_missing_inner::h12013305559594873944
                        at /home/mkpankov/rustfmt/<std macros>:8
   7:     0x5616b1a4a46e - missed_spans::_<impl>::format_missing_with_indent::hdcb181560666d24eXhf
                        at src/missed_spans.rs:25
   8:     0x5616b1a4bc9b - visitor::_<impl>::visit_fn::h6e246005e2ad32f0gId
                        at src/visitor.rs:163
   9:     0x5616b1a54c1a - visit::walk_impl_item::walk_impl_item::h12458150990348111200
                        at ../src/libsyntax/visit.rs:604
  10:     0x5616b1a521da - visitor::_<impl>::visit_impl_item::hd85067032393ced33Od
                        at src/visitor.rs:257
  11:     0x5616b1a4d85c - visit::walk_item::walk_item::h1531766977339862904
                        at ../src/libsyntax/visit.rs:287
  12:     0x5616b1a49ffd - visitor::_<impl>::visit_item::h512445a70ab5fc2dtKd
                        at src/visitor.rs:194
  13:     0x5616b1a4e76e - visit::walk_mod::walk_mod::h7884612053389459926
                        at ../src/libsyntax/visit.rs:170
  14:     0x5616b1a56a0c - visitor::_<impl>::format_separate_mod::h3d04d7cbe8f86b30ZVd
                        at src/visitor.rs:345
  15:     0x5616b1b2f80f - fmt_ast::hc4f1afd9a7cd2f29JHk
                        at src/lib.rs:279
  16:     0x5616b1b3e15a - _<impl>::build_controller::_<closure>::closure.29015
                        at src/lib.rs:392
  17:     0x7f17f9e6961c - driver::compile_input::ha14e33d94ddb50f03ba
  18:     0x7f17f9fc410b - run_compiler::h0e77504c7999109awsc
  19:     0x5616b1b3e9bd - format::h888ec83fd248cf57kSk
                        at src/lib.rs:413
  20:     0x5616b1b3fb45 - run::h9a16d1c3ba60ae3e9Sk
                        at src/lib.rs:425
  21:     0x5616b19e407c - execute::ha02357fc43f76710Hca
                        at src/bin/rustfmt.rs:68
  22:     0x5616b19e6de0 - main::h5ca3068261bd1bc80da
                        at src/bin/rustfmt.rs:74
  23:     0x7f17f85689a4 - sys_common::unwind::try::try_fn::h15885068416991889828
  24:     0x7f17f8560668 - __rust_try
  25:     0x7f17f856863f - rt::lang_start::h95fec6e24ac2c1799ix
  26:     0x5616b19e84c9 - main
  27:     0x7f17f7bec6ff - __libc_start_main
  28:     0x5616b19e0118 - _start
  29:                0x0 - <unknown>
```

**Comment by mkpankov** [comment]
Actually seems related to https://github.com/nrc/rustfmt/issues/413, if not a dup

**Comment by nrc** [comment]
Yeah, I think this is a dup of #413.

I'd be interested if you could get rustfmt running on some submodule of libcore.
