### ISSUE TITLE
`internal-error: entered unreachable code` while formatting

### ISSUE THREAD

**Issue by euclio** [nrc/rustfmt#514]
Upon running `rustfmt` with no arguments or configuration on [this file](https://github.com/Hoverbear/rust-rosetta/blob/05e04dd0552c2b4540889206179947c799caeb01/src/2048.rs).

Backtrace:
```                                                                             
euclio@apollo$ env RUST_BACKTRACE=1 cargo run -- 2048.rs
     Running `target/debug/rustfmt 2048.rs`
thread '<main>' panicked at 'internal error: entered unreachable code', src/visitor.rs:36
stack backtrace:
   1:     0x7f1d32a4bc30 - sys::backtrace::tracing::imp::write::hd35b30c9bc39e79ecet
   2:     0x7f1d32a52505 - panicking::log_panic::_<closure>::closure.39375
   3:     0x7f1d32a51f51 - panicking::log_panic::h858502af84f7e8dakex
   4:     0x7f1d32a16b43 - sys_common::unwind::begin_unwind_inner::h3c451c8cff534e2ag7r
   5:     0x5578088466c7 - sys_common::unwind::begin_unwind::begin_unwind::h13810267614759286113
                        at ../src/libstd/sys/common/unwind/mod.rs:224
   6:     0x55780886c8d5 - visitor::_<impl>::visit_expr::hcfcf61108228dfb0Fnd
                        at /home/euclio/repos/rustfmt/<std macros>:3
   7:     0x55780886fa0b - visit::walk_ty::walk_ty::h5675170167666038519
                        at ../src/libsyntax/visit.rs:359
   8:     0x55780886f76c - visit::Visitor::visit_ty::visit_ty::h2372553842394803057
                        at ../src/libsyntax/visit.rs:69
   9:     0x55780886f9da - visit::walk_ty::walk_ty::h5675170167666038519
                        at ../src/libsyntax/visit.rs:358
  10:     0x55780886f76c - visit::Visitor::visit_ty::visit_ty::h2372553842394803057
                        at ../src/libsyntax/visit.rs:69
  11:     0x55780887041d - visit::walk_fn_decl::walk_fn_decl::h1048286840031650434
                        at ../src/libsyntax/visit.rs:534
  12:     0x557808884885 - visit::walk_trait_item::walk_trait_item::h13134893299988294892
                        at ../src/libsyntax/visit.rs:574
  13:     0x557808880c1f - visitor::_<impl>::visit_trait_item::hcc6a6c25af555da8RBd
                        at src/visitor.rs:281
  14:     0x55780887bf4a - visit::walk_item::walk_item::h15196151891253916978
                        at ../src/libsyntax/visit.rs:303
  15:     0x5578088732e1 - visitor::_<impl>::visit_item::h5a63d53e5b6f4c42Kwd
                        at src/visitor.rs:193
  16:     0x55780887ccfe - visit::walk_mod::walk_mod::h15409637401976201925
                        at ../src/libsyntax/visit.rs:176
  17:     0x55780888b34c - visitor::_<impl>::format_separate_mod::h224eb710c00c1cb5LKd
                        at src/visitor.rs:393
  18:     0x55780898b93f - fmt_ast::h4afbc275b1f312c6kUk
                        at src/lib.rs:302
  19:     0x55780899a2ea - _<impl>::build_controller::_<closure>::closure.29669
                        at src/lib.rs:415
  20:     0x7f1d34349a0e - driver::compile_input::h5decbd8a607eb1ee7ba
  21:     0x7f1d3449a1bb - run_compiler::hcc56773d59769f820pc
  22:     0x55780899ab4d - format::had5590382981990ee3k
                        at src/lib.rs:436
  23:     0x55780899bd15 - run::h0a47677590cb466733k
                        at src/lib.rs:448
  24:     0x55780881185c - execute::ha02357fc43f76710Hca
                        at src/bin/rustfmt.rs:68
  25:     0x5578088145c0 - main::h5ca3068261bd1bc80da
                        at src/bin/rustfmt.rs:74
  26:     0x7f1d32a51c94 - sys_common::unwind::try::try_fn::h16605433926635505679
  27:     0x7f1d32a49958 - __rust_try
  28:     0x7f1d32a5192f - rt::lang_start::hf4afedf08032f197sbx
  29:     0x557808815cd9 - main
  30:     0x7f1d320fa60f - __libc_start_main
  31:     0x55780880d8e8 - _start
  32:                0x0 - <unknown>
Process didn't exit successfully: `target/debug/rustfmt 2048.rs` (exit code: 101)
```

**Comment by nrc** [comment]
I think this is a dup of #513

**Comment by nrc** [comment]
The stacktrace looks the same, but I don't see the kind of impl which triggered #513 in the source here.
