### ISSUE TITLE
rusmtf panics one rust/src/librustc/lib.rs

### ISSUE THREAD

**Issue by little-dude** [nrc/rustfmt#534]
```
$ export RUST_BACKTRACE=1 ; target/debug/rustfmt --write-mode=overwrite /home/corentih/rust/rust/src/librustc/lib.rs                                                        ⏎

thread '<main>' panicked at 'position 232418 does not resolve to a source location', /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/codemap.rs:962

stack backtrace:
   1:     0x561e3a85e7d0 - sys::backtrace::tracing::imp::write::h88824fa7cde382fcamt
   2:     0x561e3a860d15 - panicking::log_panic::_<closure>::closure.39651
   3:     0x561e3a860761 - panicking::log_panic::h6e56f24ee89301beimx
   4:     0x561e3a853b13 - sys_common::unwind::begin_unwind_inner::h4469900167bcc3a4efs
   5:     0x561e3a853ea8 - sys_common::unwind::begin_unwind_fmt::h3d525738d0e295e8kes
   6:     0x561e3a5ebcac - codemap::_<impl>::lookup_filemap_idx::h2c9eb868f96f4571Fkz
                        at /home/corentih/rust/rustfmt/<std macros>:8
   7:     0x561e3a5ea6d7 - codemap::_<impl>::bytepos_to_file_charpos::h1c4eeb082e9eb06bVgz
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/codemap.rs:919
   8:     0x561e3a5e9574 - codemap::_<impl>::lookup_char_pos::h65d29319b9fe0f65RYy
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/codemap.rs:728
   9:     0x561e3a58b7ee - codemap::_<impl>::lookup_char_pos_adj::h924455d6cdadb31546y
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/codemap.rs:786
  10:     0x561e3a5ebebf - codemap::_<impl>::span_to_string::h602d120787b3883cx7y
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/codemap.rs:800
  11:     0x561e3a5f9ead - diagnostic::_<impl>::emit_::h5f5b843855fa1298sLA
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/diagnostic.rs:434
  12:     0x561e3a5f6178 - diagnostic::_<impl>::emit::h949d6d813af225afbpB
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/diagnostic.rs:809
  13:     0x561e3a5f4f77 - diagnostic::_<impl>::emit::hb659111f6148e3b0evA
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/diagnostic.rs:259
  14:     0x561e3a5e1858 - diagnostic::_<impl>::span_err::h37f03a8ed2719f2e0iA
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/diagnostic.rs:140
  15:     0x561e3a619f49 - parse::parser::_<impl>::span_err::hf2ad4a573f31f840qAF
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/parse/parser.rs:1023
  16:     0x561e3a61cf1c - parse::parser::_<impl>::check_strict_keywords::hc1c5f079209a51a7g6E
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/parse/parser.rs:651
  17:     0x561e3a61c8e7 - parse::parser::_<impl>::parse_ident::habcb8abb7c8cecadPYE
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/parse/parser.rs:552
  18:     0x561e3a61d27d - parse::parser::_<impl>::parse_ident_or_self_type::h28ad139f8bc258ccz0E
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/parse/parser.rs:574
  19:     0x561e3a64113a - parse::parser::_<impl>::parse_path_segments_with_colons::h069ac13cb2c9a97ezHG
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/parse/parser.rs:1748
  20:     0x561e3a6244dc - parse::parser::_<impl>::parse_path::hb89672fc6a175e2d5AG
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/parse/parser.rs:1669
  21:     0x561e3a6498e3 - parse::parser::_<impl>::parse_bottom_expr::h861567afcd8c26cb6YG
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/parse/parser.rs:2194
  22:     0x561e3a650b93 - parse::parser::_<impl>::parse_dot_or_call_expr::hcdef921f9caa7e29isH
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/parse/parser.rs:2267
  23:     0x561e3a65fab3 - parse::parser::_<impl>::parse_prefix_expr::h181df7a5d8750254xVH
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/parse/parser.rs:2638
  24:     0x561e3a6615c3 - parse::parser::_<impl>::parse_binops::h33bb1d7af6d8c5b3d2H
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/parse/parser.rs:2645
  25:     0x561e3a662906 - parse::parser::_<impl>::parse_assign_expr::hdcb4cfb6def1739757H
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/parse/parser.rs:2734
  26:     0x561e3a660e4b - parse::parser::_<impl>::parse_expr_res::h1884aee49016ff6aezI
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/parse/parser.rs:2976
  27:     0x561e3a60965c - parse::parser::_<impl>::parse_expr_nopanic::h02a039a9973a46061yI
                        at /home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master/syntex_syntax/src/parse/parser.rs:2969
  28:     0x561e3a44c7b5 - macros::rewrite_macro::h5cc5e97297b5edcdODk
                        at src/macros.rs:81
  29:     0x561e3a440ea8 - expr::_<impl>::rewrite::h569e65ce67fefd00c1g
                        at src/expr.rs:153
  30:     0x561e3a4c32bb - chains::rewrite_chain::h9e4ba19f4d0572c7Xmk
                        at src/chains.rs:52
  31:     0x561e3a440e62 - expr::_<impl>::rewrite::h569e65ce67fefd00c1g
                        at src/expr.rs:148
  32:     0x561e3a4c50e1 - expr::rewrite_unary_prefix::h14833049736916699316
                        at src/expr.rs:1474
  33:     0x561e3a4c5517 - expr::rewrite_expr_addrof::hf90f6440dc81f81c50i
                        at src/expr.rs:1564
  34:     0x561e3a441132 - expr::_<impl>::rewrite::h569e65ce67fefd00c1g
                        at src/expr.rs:170
  35:     0x561e3a4b2772 - expr::rewrite_call_inner::_<closure>::closure.22622
                        at src/expr.rs:1143
  36:     0x561e3a4b45ed - lists::_<impl>::next::_<closure>::closure.22631
                        at src/lists.rs:448
  37:     0x561e3a4b2f5a - option::_<impl>::map::map::h366828981687747589
                        at ../src/libcore/option.rs:425
  38:     0x561e3a4b2edc - lists::_<impl>::next::h12847556154958005643
                        at src/lists.rs:352
  39:     0x561e3a4b5305 - vec::_<impl>::extend_desugared::extend_desugared::h12701610139391031837
                        at ../src/libcollections/vec.rs:1317
  40:     0x561e3a4b2d11 - vec::_<impl>::from_iter::from_iter::h2435088377063126214
                        at ../src/libcollections/vec.rs:1241
  41:     0x561e3a4b2827 - iter::Iterator::collect::collect::h9024346403631925109
                        at ../src/libcore/iter.rs:809
  42:     0x561e3a4b1512 - expr::rewrite_call_inner::h17478282434344676738
                        at src/expr.rs:1146
  43:     0x561e3a4b0acf - expr::rewrite_call::_<closure>::closure.22608
                        at src/expr.rs:1088
  44:     0x561e3a4b5b1e - utils::binary_search::h5535779561622130205
                        at src/utils.rs:235
  45:     0x561e3a4b0a06 - expr::rewrite_call::h2845418059466787788
                        at src/expr.rs:1093
  46:     0x561e3a44006e - expr::_<impl>::rewrite::h569e65ce67fefd00c1g
                        at src/expr.rs:58
  47:     0x561e3a4b2772 - expr::rewrite_call_inner::_<closure>::closure.22622
                        at src/expr.rs:1143
  48:     0x561e3a4b45ed - lists::_<impl>::next::_<closure>::closure.22631
                        at src/lists.rs:448
  49:     0x561e3a4b2f5a - option::_<impl>::map::map::h366828981687747589
                        at ../src/libcore/option.rs:425
  50:     0x561e3a4b2edc - lists::_<impl>::next::h12847556154958005643
                        at src/lists.rs:352
  51:     0x561e3a4b2959 - vec::_<impl>::from_iter::from_iter::h2435088377063126214
                        at ../src/libcollections/vec.rs:1229
  52:     0x561e3a4b2827 - iter::Iterator::collect::collect::h9024346403631925109
                        at ../src/libcore/iter.rs:809
  53:     0x561e3a4b1512 - expr::rewrite_call_inner::h17478282434344676738
                        at src/expr.rs:1146
  54:     0x561e3a4b0acf - expr::rewrite_call::_<closure>::closure.22608
                        at src/expr.rs:1088
  55:     0x561e3a4b5b1e - utils::binary_search::h5535779561622130205
                        at src/utils.rs:235
  56:     0x561e3a4b0a06 - expr::rewrite_call::h2845418059466787788
                        at src/expr.rs:1093
  57:     0x561e3a44006e - expr::_<impl>::rewrite::h569e65ce67fefd00c1g
                        at src/expr.rs:58
  58:     0x561e3a43dbb2 - visitor::_<impl>::visit_stmt::h79031d2c03050367Drd
                        at src/visitor.rs:50
  59:     0x561e3a443275 - visitor::_<impl>::visit_block::h6f0d4851dddb3cb2itd
                        at src/visitor.rs:83
  60:     0x561e3a446371 - visitor::_<impl>::visit_fn::h3776f1e566e5ca58dyd
                        at src/visitor.rs:164
  61:     0x561e3a43f39c - visitor::_<impl>::visit_item::h2b452380e40c1175lAd
                        at src/visitor.rs:271
  62:     0x561e3a452040 - visitor::_<impl>::walk_mod_items::hf001ebd7c64d193dRNd
                        at src/visitor.rs:422
  63:     0x561e3a4526ec - visitor::_<impl>::format_separate_mod::h439aec81b29ad9563Qd
                        at src/visitor.rs:450
  64:     0x561e3a55843b - fmt_ast::h6b9c797c174a946154k
                        at src/lib.rs:288
  65:     0x561e3a5661c4 - format::h22d851fd0f12d1bcPbl
                        at src/lib.rs:379
  66:     0x561e3a566b9d - run::h89c95a778e46a848Ccl
                        at src/lib.rs:393
  67:     0x561e3a3c3706 - execute::h8c2c3b9c056bd44b1ca
                        at src/bin/rustfmt.rs:77
  68:     0x561e3a3d48db - main::h96228aa6507c7937pea
                        at src/bin/rustfmt.rs:85
  69:     0x561e3a8604a4 - sys_common::unwind::try::try_fn::h13318919485096579891
  70:     0x561e3a85dd08 - __rust_try
  71:     0x561e3a86013f - rt::lang_start::hb77b7d2bde6bcbecqjx
  72:     0x561e3a3d5fe9 - main
  73:     0x7fcfa5c2d60f - __libc_start_main
  74:     0x561e3a3bf258 - _start
  75:                0x0 - <unknown>

```

In `/home/corentih/.cargo/git/checkouts/syntex-b2c5d63b3d829888/master`, `git log` shows that last commit is `176ca5d8add606fac8d503b10c89ddb82f02d92b`. so it's failing here exactly: https://github.com/serde-rs/syntex/blob/176ca5d8add606fac8d503b10c89ddb82f02d92b/syntex_syntax/src/codemap.rs#L962

**Comment by marcusklaas** [comment]
Reduced testcase:
```rust
fn main() {
    x!(fn);
}
```

**Comment by marcusklaas** [comment]
Closed by https://github.com/nrc/rustfmt/pull/543.
