### ISSUE TITLE
Rustfmt panics on rust-doom

### ISSUE THREAD

**Issue by steveklabnik** [nrc/rustfmt#546]
https://github.com/cristicbz/rust-doom has several crates. One of them causes `rustfmt` to panic:

```
steve@warmachine:~/src/rust-doom$ rustfmt src/math/lib.rs 
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: IllFormedSpan(Span { lo: BytePos(14654), hi: BytePos(14588), expn_id: ExpnId(4294967295) })', ../src/libcore/result.rs:738
```

backtrace:

```
stack backtrace:
   1:     0x7f79f0f452b0 - sys::backtrace::tracing::imp::write::h1fe79f3711caca0eUnt
   2:     0x7f79f0f477f5 - panicking::log_panic::_<closure>::closure.39701
   3:     0x7f79f0f47241 - panicking::log_panic::hffc6d029fed602571nx
   4:     0x7f79f0f3a5f3 - sys_common::unwind::begin_unwind_inner::h7045c1c64d9ab8edYgs
   5:     0x7f79f0f3a988 - sys_common::unwind::begin_unwind_fmt::h40ee994bfe85f7a54fs
   6:     0x7f79f0f44981 - rust_begin_unwind
   7:     0x7f79f0f74c3f - panicking::panic_fmt::h4c8d12e3c05f3b8cZEK
   8:     0x7f79f0acd073 - result::_<impl>::unwrap::unwrap::h10268982511282634739
                        at ../src/libcore/macros.rs:28
   9:     0x7f79f0b6df6c - lists::_<impl>::next::_<closure>::closure.22100
                        at src/lists.rs:371
  10:     0x7f79f0b6d9ea - option::_<impl>::map::map::h7900555215386721759
                        at ../src/libcore/option.rs:426
  11:     0x7f79f0b6d96c - lists::_<impl>::next::h8106422578337959668
                        at src/lists.rs:352
  12:     0x7f79f0b6feb5 - vec::_<impl>::extend_desugared::extend_desugared::h13268842128361657062
                        at ../src/libcollections/vec.rs:1313
  13:     0x7f79f0b6d7a1 - vec::_<impl>::from_iter::from_iter::h1433151953203297080
                        at ../src/libcollections/vec.rs:1237
  14:     0x7f79f0b6d2b7 - iter::Iterator::collect::collect::h16685775291698171214
                        at ../src/libcore/iter.rs:809
  15:     0x7f79f0b473f8 - items::_<impl>::rewrite_where_clause::hffd7e437ed82701dCWe
                        at src/items.rs:984
  16:     0x7f79f0b56d68 - items::_<impl>::format_generics::h7462211cf813a535jQe
                        at src/items.rs:876
  17:     0x7f79f0b2e498 - items::_<impl>::format_struct::h5756ccce00d56517HHe
                        at src/items.rs:791
  18:     0x7f79f0b245e3 - visitor::_<impl>::visit_item::h8e2500a73891e220NAd
                        at src/visitor.rs:219
  19:     0x7f79f0b376b0 - visitor::_<impl>::walk_mod_items::h8e07052540254fd0lOd
                        at src/visitor.rs:431
  20:     0x7f79f0b37d5d - visitor::_<impl>::format_separate_mod::hda019cc4e4ba6314xRd
                        at src/visitor.rs:459
  21:     0x7f79f0c3c768 - fmt_ast::hef2cb21f40545581d6k
                        at src/lib.rs:301
  22:     0x7f79f0c4a812 - format::ha2c51b909a571244Ycl
                        at src/lib.rs:397
  23:     0x7f79f0c4d56d - run::hf798d91a6a6ede9b6dl
                        at src/lib.rs:411
  24:     0x7f79f0aa89dc - execute::hf5e6f85e3a5eda9adda
                        at src/bin/rustfmt.rs:101
  25:     0x7f79f0ab9cfb - main::h08f16d83ca7f571cffa
                        at src/bin/rustfmt.rs:109
  26:     0x7f79f0f46f84 - sys_common::unwind::try::try_fn::h6992056864475615854
  27:     0x7f79f0f447e8 - __rust_try
  28:     0x7f79f0f46c1f - rt::lang_start::h58cfae38546804729kx
  29:     0x7f79f0abb409 - main
  30:     0x7f79f04c7b44 - __libc_start_main
  31:     0x7f79f0aa43c8 - <unknown>
  32:                0x0 - <unknown>
```

**Comment by cristicbz** [comment]
I found what causes this. rustfmt panics on a tuple struct with a where clause. Minimal example:

```rust
struct Foo<T>(T) where T: PartialEq;
```
